repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.8.2"
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args:
          [
            --install-types,
            --non-interactive,
            --follow-imports=silent,
            --ignore-missing-imports,
            --allow-redefinition,
            --python-version=3.11,
          ]
